Refactor xres namespace for wayland
regolith-linux/regolith-look-default pull request #5
Opened 2023-01-14 20:28 UTC by kgilmer

Rename `i3-wm` to `wm` in Xres keys for compat w/ wayland

2023-01-14 22:09 UTC, SoumyaRanjanPatnaik requested changes
Change filename from `i3-wm` -> `wm` ?

2023-01-15 17:59 UTC, kgilmer commented
good catch, fixed

2023-01-16 10:58 UTC, SoumyaRanjanPatnaik approved these changes

2023-01-16 10:58 UTC, SoumyaRanjanPatnaik commented
LGTM

2023-02-26 18:25 UTC, merged